# Generated by Django 5.2.3 on 2025-07-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0004_atleta_deporte_profesor_delete_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otras_actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('profesor', models.CharField(max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
