# Generated by Django 5.2.3 on 2025-07-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0005_otras_actividades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Otras_actividades',
            new_name='Otra_actividad',
        ),
    ]
