# Generated by Django 5.2.3 on 2025-07-20 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0006_rename_otras_actividades_otra_actividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otra_actividad',
            name='descripcion',
        ),
    ]
